blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Discussions
    url: https://github.com/CosmoDevs/cosmoslive/discussions
    about: Please ask and answer questions here instead of creating an issue.
